### ISSUE TITLE
Setup real-time algorithm controller

### ISSUE THREAD

**Issue by Grenadingue** [Grenadingue/2-wheels-1-arm#12]
Depends on #11 
- [ ] Setup Node.js/C++ binding with `node-gyp`
- [ ] Setup Socket.io server in `/library/socket.io.js` and `/controller/real-time.js`

Useful ressources:
- https://nodejs.org/api/addons.html

**Comment by pachakamakk** [comment]
Regarding the parameters passed to the c++ code:
Is it an array of parameters like param[0] = cycles max, param[1] = mutation_rate, etc...
Or a structure directly like s_param { int cycles_max, float mutation_rate, etc... }

**Comment by Grenadingue** [comment]
I think the best option for passing parameters is an array of string  
Created kinda like this in node:

```
var parameters = [ 'population_size=200', 'mutation_rate=2%', ... ];
```

And converted kinda like this in c++:

```
std::list<std::string> parameters;

parameters.push_back("population_size=200");
parameters.push_back("mutation_rate=2%");
...
```

[Here](https://github.com/Grenadingue/2-wheels-1-arm/blob/%2316_setup_c%2B%2B_code_skeleton/algorithm/cpp/WebServerBridge.cpp#L38) you can see how it is actually (faked) setup in c++

**Comment by pachakamakk** [comment]
Is it really usefull to put the form "key=value" in the array? Makes useless parsing in the c++ side, when some constants like:

 param[POPULATION_SIZE] = 200; param[MUTATION_RATE] = 0.6;

could make things easier using the same principle.

**Comment by Grenadingue** [comment]
Agree, will be easier like this. Let's do a classic javascript object on node.js side and an `std::map` on c++ side; usable like in your example
