### ISSUE TITLE
Develop first algorithm implementation

### ISSUE THREAD

**Issue by Grenadingue** [Grenadingue/2-wheels-1-arm#19]
## Coding style

- Protect file headers with `#ifndef FOO_HPP_` `# define FOO_HPP_` `#endif // !FOO_HPP_`
- Preprocessor instructions are indented with a space after an `#if`, desindented after and `#endif`, like the previous `# define`
- In a `class`, `protected` and `private` members name __*always*__ start with an `_` underscore
- In a `class Foo`, for an attribute `int _bar` the getter/setter syntax will be
  - `int bar() const`
  - `void setBar()`
- Use as much as possible initializer lists in constructors `class Foo { Foo() : _bar(42) {} }`
- Skip a line before the `:` in an initializer list

## Fitness

- [x] Create class `Fitness`
- [x] Implement `public` empty constructor and destructor in both `.hpp` and `.cpp`
- [x] Implement `int _score` in `Fitness`, initialize it at `0` at construction
- [x] Implement `_score` getter and setter 
- [x] Create a `private` `Fitness *_fitness` in `Individual`
- [x] Initialize the pointer with a `new Fitness` in `Individual` constructors
- [x] Create a `public` `Fitness &fitness()` getter in `Individual`

---

## Genome

- [x] Remove `Genome` templating in [`Genome.hpp`](/algorithm/source/Genome.hpp)
- [x] Remove `public: typedef std::list<gene_t> genes_t;`
- [x] Implement `struct gene_t` in `Genome`, like in [2w1a pseudo code](https://github.com/Grenadingue/2-wheels-1-arm/blob/%234_describe_a_simple_algorithm_for_the_1st_implementation/documents/algorithm_pseudo_code.md#data-encoding) (without fake and debug prints)
- [x] Replace `genes_t _genes;` by `std::vector<gene_t> _genes;`
- [x] Implement `gene_t &operator[](int pos)` and `gene_t &operator[](unsigned int pos)`

---

## Genetic algorithm controller

Look at `class World` in [`World.hpp`](/algorithm/source/World.hpp) and [`World.cpp`](/algorithm/source/World.cpp), `GeneticAlgoController` inherits from it

Implement methods (empty if needed), and attributes

```c++
class GeneticAlgoController {
  std::vector<Individual *> _population;

  // fitness
  void _rateIndividual(Individual &individual);
  void _sortPopulationByScoreDesc(); // via Fitness &Individual::fitness().score();

  // generate offspring
  std::vector<Individual *> *_generateOffspring();
  std::pair<Individual *, Individual *> _selectParents(); // pick two individuals for reproduction
  Individual *_itsSexTime(std::pair<Individual *, Individual *> &parents); // generate child from parents
  void _mutateChildGenome(Individual &child); // apply mutation probability
  void _insertChildrenInPopulation(std::vector<Individual *> *); // in _population

  // kill a part of the population
  void _harshLife();

  // current best solution
  Individual *_bestSolution(); // from Individual::fitness().score()
}
```

Keep in mind that the algorithm must always work, even if you need to simulate something you don't have. Put comments where there is this kind of code.

Implement the previous methods, except `_rateIndividual()`. You can get inspiration from the [string finder algorithm pseudo code](https://github.com/Grenadingue/2-wheels-1-arm/blob/%234_describe_a_simple_algorithm_for_the_1st_implementation/documents/algorithm_pseudo_code.md#string-finder-algorithm). Be smart while taking inspiration from this algorithm, implementation is different than 2w1a one.

---

## Depends

#16 and #4

**Comment by pachakamakk** [comment]
Fitness to be fully implemented
