### ISSUE TITLE
Implement algorithm logger

### ISSUE THREAD

**Issue by Grenadingue** [Grenadingue/2-wheels-1-arm#32]
For `WritableResultModel` implement

```c++
std::ofstream &WritableResultModel::operator〈〈(std::ofstream &file, const WritableResultModel &)
```

Use `WritableResultModel` inside `void BackupDataController::_workLoop()` kind of like this

```c++
// result in a ResultModel *
WritableResultModel &json = *result;
std::ofstream file;
// ...
file << json;
```

Simulate the workability of `WritableResultModel` in the `main()`

You will need to add the following attributes in `ResultModel` in order to use them
``` c++
class ResultModel
{
protected:
  int _iteration;
  int _theoreticalMaxScore;
  int _maxScore;
  double _averageScore;
  int _worstScore;
  // ...
}
```

Since `theoreticalMaxScore` will always has the same value, we will only write it once in the file. For that we will trick a bit. If `theorethicalMaxScore` is not `-1`, write only this value as json, if it is `-1` write all the others.

Written data must be in the form
```json
{
  "theoreticalMaxScore": 400,
  "results": [
    {
      "iteration": 0,
      "maxScore": 1,
      "averageScore": 0.5,
       "worstScore": 0
    },
    {
      "iteration": 1,
      "maxScore": 3,
      "averageScore": 1.5,
       "worstScore": 0
    }
  ]
}
```

Open file on Node.js side to check that the syntax is right.

Also, implement the empty methods
```c++
  ResultModel::ResultModel(const ResultModel &)
  ResultModel::ResultModel(const ResultModel *)
  ResultModel::ResultModel &operator=(const ResultModel &)
  ResultModel::ResultModel &operator=(const ResultModel *)
```

Remove
```c++
ResultModel::ResultModel()
```

And add the following
```c++
ResultModel::ResultModel(int theoreticalMaxScore)
ResultModel::ResultModel(int iteration, int maxScore, double averageScore, int worstScore)
```

**Comment by pachakamakk** [comment]
Bails are done
