### ISSUE TITLE
Design fixes

### ISSUE THREAD

**Issue by Grenadingue** [Grenadingue/2-wheels-1-arm#43]
- [x] Put algorithm parameters legends beside forms
- [x] Add one more line of algorithm parameters
- [x] Graph size is hard coded for fullscreen, make it fit the window size
- [x] Put a pre-existant bootstrap style to the "Select a previous simulation" list
- "Launch simulation" button
  - [x] Replace the text on the button by "Display backup" when "Select a previous simulation" is selected
  - [x] Still display "Launch simulation" when "Input the params you want" is selected
- Replace
  - "Input the params you want" by "Configure algorithm launcher"
  - "Select a previous simulation" by "Select a simulation backup"

**Comment by AdriVig** [comment]
Issue: #46
