### ISSUE TITLE
Set y axle focus on graph

### ISSUE THREAD

**Issue by Grenadingue** [Grenadingue/2-wheels-1-arm#44]
- [x] Create a new socket.io event in webapp, `set y axle`, receiving as parameter an y max value
- [x] Set the y axle focus on the graph to be fixed to the given y max value

Why ?

The y max value is the theoretical maximum score, so it's to get a full vision over the score progression

**Comment by tomacf** [comment]
The expected behavior from frontside will be
client->emit LaunchSimulation
then as long as I will not receive the "set y axle" I will not launch anything
as soon as I will receive this event and configure my graph I will listen and wait for the "new_iteration" event

**Comment by tomacf** [comment]
Key expected with example value on the event : 
{yMax: 100}
