### ISSUE TITLE
Launch a vrep pool before starting algorithm

### ISSUE THREAD

**Issue by Grenadingue** [Grenadingue/2-wheels-1-arm#55]
- Add vrep executable full path to the config file
- In frontend, use a parameter field to specify a number of vrep instances to launch
- Send the value of the previously created field to web server
- In web server, launch the N vrep instances before starting the c++ algorithm
  - Launch a vrep instance on a generated port
    - Also specify in parameters the `2w1a.ttt` scene
  - Add the generated port to a list
  - Catch vrep process close event
    - If process failed, remove the port from the list, an try to launch another instance with another port
  - When all vrep process have spawned
    - Concatenate the list of all the ports in a string like `4000,4001,4002`
    - Put the created string in the algorithm parameters as `vrepPool`
    - Then the algorithm can be launched

Usefull: http://www.coppeliarobotics.com/helpFiles/en/commandLine.htm

Note: The scene path must be the full path

**Comment by tomacf** [comment]
Current advancement :
- [x] Node.js take v-rep path as parameter
- [x] Node.js launch X instances of V-Rep using different port
- [x] Those port are sent to the cpp server
- [x] Frontside allow the user to set the number of v-rep instances and send it to the Node.js
- [x] Catching V-Rep error
- [x] Manually strop V-Rep instances
