### ISSUE TITLE
Create all needed mathematics classes

### ISSUE THREAD

**Issue by Grenadingue** [Grenadingue/2-wheels-1-arm#57]
- Create `class Vector`

Note: Existing maths classes are
  - [Maths](https://github.com/Grenadingue/2-wheels-1-arm/blob/master/algorithm/source/Maths.hpp)
  - [Degrees](https://github.com/Grenadingue/2-wheels-1-arm/blob/master/algorithm/source/Degrees.hpp)
  - [Radians](https://github.com/Grenadingue/2-wheels-1-arm/blob/master/algorithm/source/Maths.hpp/Radians.hpp)

Note2: To use the libmath(s), include the library (like the pthead one in examples) in
  - [binding.gyp](https://github.com/Grenadingue/2-wheels-1-arm/blob/master/algorithm/binding.gyp#L41)
  - [CMakeLists.txt](https://github.com/Grenadingue/2-wheels-1-arm/blob/master/algorithm/CMakeLists.txt#L68)

**Comment by AdriVig** [comment]
On veut : la longueur des vecteurs, leurs coordonnées x et y, l'angle entre les deux.

```
vecteur 1 : x1, y1 et x2, y2
vecteur 2 : x3, y3 et x4, y4
```

Longueur des vecteurs :

```
pow_carre_x_1 = pow((x2 - x1), 2);
pow_carre_y_1 = pow((y2 - y1), 2);

length_vector_1 = sqrt(pow_carre_x + pow_carre_y);

pow_carre_x_2 = pow((x4 - x3), 2);
pow_carre_y_2 = pow((y4 - y3), 2);

length_vector_2 = sqrt(pow_carre_x_2 + pow_carre_y_2);
```

Coordonnées X et Y des vecteurs :

```
x1_vector = x2 - x1;
y1_vector = y2 - y1;

x2_vector = x4 - x3;
y2_vector = x4 - x3;
```

Calcul de l'angle entre les deux vecteurs :

```
Na = sqrt(pow(x1_vector, 2) + pow(y1_vector, 2));
Nb = sqrt(pow(x2_vector, 2) + pow(y2_vector, 2));
C = (x1_vector * x2_vector + y1_vector * y2_vector) / (Na * Nb);

BÂC = acos(C);
```

**Comment by AdriVig** [comment]
Class Vector :

```
float x1, y1, x2, y2;

Vector vector1 = new Vector(x1, y1);
Vector vector2 = new Vector(x2, y2);

float lenght = vector*.getLength();
Pair<float x, float y> coordinates = vector*.getCoordinates();
float angle = vector*.getAngle(vector*);
```
