### ISSUE TITLE
Front-end fixes

### ISSUE THREAD

**Issue by Grenadingue** [Grenadingue/2-wheels-1-arm#58]
*Please make a commit for each point*

---

- ## Javascript check before emitting "start algo"
- [x] Check that all the fields from the algorithm launcher are filled before allow emitting "start algo" event

---

- ## Update title
- [x] Add " - Genetic Algorithms" after "AI - Evolution programs"

---

- ## Update legend on graph
- [x] Grow legend

---

- ## Update line colors
- [x] Make line colors follow a color gradient pattern
- [x] Color pattern and line meaning must consistent for easy understanding

---

- ## Add a field to the algo launcher
- [x] Add `errorAcceptabilityRate`

---

- ## Pre-fill all fields of the algorithm launcher
- [x] Population size : 200
- [x] Population renewal rate : 0.33
- [x] Mutation rate : 0.01
- [x] Simulation cycles : 3
- [x] Vrep pool size : 4
- [x] Error acceptability rate : 0.07

**Comment by AdriVig** [comment]
Issue : #58
